---
title: "mimic_IV_check"
format: html
---


```{r}
library(dplyr)
```


```{r}
data_3_admi <- read.csv("mimic-iii-clinical-database-1.4/ADMISSIONS.csv")
length(data_3_admi$SUBJECT_ID) - length(unique(data_3_admi$SUBJECT_ID)) # 46520 uniq
```

**Comment** 12456 not unique 

```{r}
data_3_ICU <- read.csv("mimic-iii-clinical-database-1.4/ICUSTAYS.csv")
length(unique(data_3_ICU$SUBJECT_ID)) # 46476 

sum(is.na(data_3_ICU))
```

```{r}
table(data3_p$EXPIRE_FLAG)

# 
suject_ID_alive <- data3_p[data3_p$EXPIRE_FLAG == 0, "SUBJECT_ID"]

infor_los <-data_3_ICU[,c("LOS","SUBJECT_ID","HADM_ID","ICUSTAY_ID" )]

result_df <- left_join(suject_ID_alive, infor_los, 
                       by = "SUBJECT_ID")|>
  na.omit()

result_df

hist(result_df$LOS,breaks = 1000)
    
summary(result_df$LOS)

result_df[result_df$LOS == 0.0003,]

data3_p[data3_p$SUBJECT_ID == 4226,]

result_df[result_df$LOS < 0.5 |result_df$LOS >60 ,]


infor_pre <- data_3_admi[,c("SUBJECT_ID","HADM_ID","RELIGION")]
result_df_new <- left_join(result_df, infor_pre, 
                       by = c("SUBJECT_ID","HADM_ID"))|>
  na.omit()|>
  mutate(RELIGION = as.factor(RELIGION))


model <- lm(LOS~RELIGION,data=result_df_new)
summary(model)
```


```{r}
sum(unique(data_3_admi$SUBJECT_ID) %in% unique(data_3_ICU$SUBJECT_ID))

## 46476 uniqe  data_3_admi  find in data_3_ICU  for SUBJECT_ID 
```


```{r}
hist(data_3_ICU$LOS,breaks = 1000)
summary(data_3_ICU$LOS) ## 10 NA  ， 
```


```{r}


data_3_ICU[data_3_ICU$LOS == 0.0001, ]|>
  na.omit() # 12 second 

# 14780	
```




```{r}
data3_p <- read_csv("mimic-iii-clinical-database-1.4/PATIENTS.csv")
data3_p[data3_p$SUBJECT_ID == 14780,]
```

```{r}

data3_diag_ICD <- read.csv("mimic-iii-clinical-database-1.4/DIAGNOSES_ICD.csv")
head(data3_diag_ICD,100)
length(unique(data3_diag_ICD$SUBJECT_ID))
```


```{r}
data_ICD <- read_csv("mimic-iii-clinical-database-1.4/D_ICD_DIAGNOSES.csv")
data_ICD
data_ICD[data_ICD$ICD9_CODE == "0953",]
```
